### ISSUE TITLE
连线时鼠标位置和箭头位置不一致

### ISSUE THREAD

**Issue by XlousZ** [ongdb-contrib/graphene#1]
![image](https://github.com/ongdb-contrib/graphene/assets/20225492/6da1b873-3e15-4ec8-bc2b-f3bc7a81bf49)

**Comment by crazyyanchao** [comment]
刷新一下页面再试试应该就可以了，缩放时有可能导致坐标计算出差错导致看到的不清晰

**Comment by crazyyanchao** [comment]
@XlousZ 刷新一下页面再试试应该就可以了，缩放时有可能导致坐标计算出差错导致看到的不清晰
